fieldLayouts:
  cd9787fc-4916-4c95-85a2-5cff1f7c6a62:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8dedbd60-f189-466e-8326-79936ee0828b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09c149d4-cfcf-4cfc-8e0c-0ca614ee5831
        userCondition: null
fs: hardDisk
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
